# Generated by OmopViewer 0.4.0
# Be careful editing this file

library(bslib)
library(CohortCharacteristics)
library(dplyr)
library(DT)
library(ggplot2)
library(gt)
library(IncidencePrevalence)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(plotly)
library(purrr)
library(readr)
library(rlang)
library(shiny)
library(shinycssloaders)
library(shinyTree)
library(shinyWidgets)
library(sortable)
library(tidyr)
library(visOmopResults)
library(yaml)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "shinyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "data", "preprocess.R"))
}

# uncomment to load the raw data
# rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "data"))

# load shiny data
load(fileData)

data$summarise_characteristics <- data$summarise_characteristics |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (.data$group_level %in% c("bexsero", "trumenba", "menveo", "nimenrix")))
  )

data$prevalence <- data$prevalence |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (stringr::str_detect(.data$group_level, "bexsero") ))
  ) |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (stringr::str_detect(.data$group_level, "trumenba") ))
  ) |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (stringr::str_detect(.data$group_level, "menveo") ))
  ) |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (stringr::str_detect(.data$group_level, "nimenrix") ))
  )

prevalence_setting <- omopgenerics::settings(data$prevalence) |>
  dplyr::mutate(
    denominator_age_group = 
      case_when(
        denominator_age_group == "1 to 1" ~ "1",
        denominator_age_group == "2 to 2" ~ "2",
        denominator_age_group == "18 to 18" ~ "18",
        T ~ denominator_age_group
      )
  )

data$prevalence <- data$prevalence |>
  omopgenerics::newSummarisedResult(
    settings = prevalence_setting
  )

data$prevalence_attrition <- data$prevalence_attrition |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (stringr::str_detect(.data$group_level, "bexsero") ))
  ) |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (stringr::str_detect(.data$group_level, "trumenba") ))
  ) |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (stringr::str_detect(.data$group_level, "menveo") ))
  ) |>
  dplyr::filter(
    !((!.data$cdm_name %in% c("CPRD_GOLD")) & (stringr::str_detect(.data$group_level, "nimenrix") ))
  )

prevalence_attrition_setting <- omopgenerics::settings(data$prevalence_attrition) |>
  dplyr::mutate(
    denominator_age_group = 
      case_when(
        denominator_age_group == "1 to 1" ~ "1",
        denominator_age_group == "2 to 2" ~ "2",
        denominator_age_group == "18 to 18" ~ "18",
        T ~ denominator_age_group
      )
  )

data$prevalence_attrition <- data$prevalence_attrition |>
  omopgenerics::newSummarisedResult(
    settings = prevalence_attrition_setting
  )

# source functions
source(file.path(getwd(), "functions.R"))
