# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    summarise_characteristics = FALSE,
    prevalence = FALSE,
    prevalence_attrition = FALSE
  )

  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observeEvent(c("BIFAP", "CPRD_GOLD", "DK-DHR", "FinOMOP-THL", "NAJS Croatia", "SIDIAP"),
    {
      updateButtons$summarise_omop_snapshot <- FALSE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(c("cdm", "general", "observation_period"),
    {
      updateButtons$summarise_omop_snapshot <- FALSE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]]
  })
  getSummariseOmopSnapshotTidy <- shiny::reactive({
    tidyDT(getSummariseOmopSnapshotData(), input$summarise_omop_snapshot_tidy_columns, input$summarise_omop_snapshot_tidy_pivot_estimates)
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    getSummariseOmopSnapshotTidy()
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseOmopSnapshotData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_observation_period_cdm_name,
    {
      updateButtons$summarise_observation_period <- FALSE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_observation_period_observation_period_ordinal,
    {
      updateButtons$summarise_observation_period <- FALSE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_observation_period_variable_name,
    {
      updateButtons$summarise_observation_period <- FALSE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_observation_period_estimate_name,
    {
      updateButtons$summarise_observation_period <- FALSE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_observation_period <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]]
  })
  getSummariseObservationPeriodTidy <- shiny::reactive({
    tidyDT(getSummariseObservationPeriodData(), input$summarise_observation_period_tidy_columns, input$summarise_observation_period_tidy_pivot_estimates)
  })
  output$summarise_observation_period_tidy <- DT::renderDT({
    getSummariseObservationPeriodTidy()
  })
  output$summarise_observation_period_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseObservationPeriodData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod()
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )
  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_characteristics_cdm_name,
    {
      updateButtons$summarise_characteristics <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_cohort_name,
    {
      updateButtons$summarise_characteristics <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_sex,
    {
      updateButtons$summarise_characteristics <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_age_group,
    {
      updateButtons$summarise_characteristics <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_age,
    {
      updateButtons$summarise_characteristics <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_variable_name,
    {
      updateButtons$summarise_characteristics <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_characteristics_estimate_name,
    {
      updateButtons$summarise_characteristics <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_characteristics <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$sex %in% input$summarise_characteristics_sex,
        .data$age_group %in% input$summarise_characteristics_age_group,
        .data$age %in% input$summarise_characteristics_age
      )
  })
  getSummariseCharacteristicsTidy <- shiny::reactive({
    tidyDT(getSummariseCharacteristicsData(), input$summarise_characteristics_tidy_columns, input$summarise_characteristics_tidy_pivot_estimates)
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    getSummariseCharacteristicsTidy()
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCharacteristicsData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # prevalence -----
  ## update message if filter is changed
  shiny::observeEvent(input$prevalence_cdm_name,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_outcome_cohort_name,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_prevalence_start_date,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_prevalence_end_date,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_analysis_interval,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("FALSE",
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("FALSE",
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("point prevalence",
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_denominator_age_group,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_denominator_days_prior_observation,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_denominator_end_date,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("FALSE",
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_denominator_sex,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("2017-01-01",
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("None",
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("0 to Inf",
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_variable_name,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_estimate_name,
    {
      updateButtons$prevalence <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$prevalence, {
    if (updateButtons$prevalence == TRUE) {
      output$update_message_prevalence <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_prevalence <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_prevalence, {
    updateButtons$prevalence <- FALSE
  })

  ## get prevalence data
  getPrevalenceData <- shiny::eventReactive(input$update_prevalence, {
    data[["prevalence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$prevalence_cdm_name,
        .data$variable_name %in% input$prevalence_variable_name,
        .data$estimate_name %in% input$prevalence_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$outcome_cohort_name %in% input$prevalence_outcome_cohort_name) |>
      omopgenerics::filterAdditional(
        .data$prevalence_start_date %in% input$prevalence_prevalence_start_date,
        .data$prevalence_end_date %in% input$prevalence_prevalence_end_date,
        .data$analysis_interval %in% input$prevalence_analysis_interval
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_complete_database_intervals %in% "FALSE",
        .data$analysis_full_contribution %in% "FALSE",
        .data$analysis_type %in% "point prevalence",
        .data$denominator_age_group %in% input$prevalence_denominator_age_group,
        .data$denominator_days_prior_observation %in% input$prevalence_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$prevalence_denominator_end_date,
        .data$denominator_requirements_at_entry %in% "FALSE",
        .data$denominator_sex %in% input$prevalence_denominator_sex,
        .data$denominator_start_date %in% "2017-01-01",
        .data$denominator_target_cohort_name %in% "None",
        .data$denominator_time_at_risk %in% "0 to Inf"
      )
  })
  getPrevalenceTidy <- shiny::reactive({
    tidyDT(getPrevalenceData(), input$prevalence_tidy_columns, input$prevalence_tidy_pivot_estimates)
  })
  output$prevalence_tidy <- DT::renderDT({
    getPrevalenceTidy()
  })
  output$prevalence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getPrevalenceData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getPrevalenceTable <- shiny::reactive({
    res <- getPrevalenceData()
    res |>
      IncidencePrevalence::tablePrevalence(
        header = input$prevalence_table_header,
        groupColumn = input$prevalence_table_group_column,
        hide = input$prevalence_table_hide,
        settingsColumn = omopgenerics::settingsColumns(res)
      )
  })
  output$prevalence_table <- gt::render_gt({
    getPrevalenceTable()
  })
  output$prevalence_table_download <- shiny::downloadHandler(
    filename = paste0("table_prevalence.", input$prevalence_table_format),
    content = function(file) {
      gt::gtsave(getPrevalenceTable(), file)
    }
  )
  getPrevalencePlot <- shiny::reactive({
    getPrevalenceData() |>
      IncidencePrevalence::plotPrevalence(
        x = input$prevalence_plot_x,
        facet = input$prevalence_plot_facet,
        colour = input$prevalence_plot_colour,
        ribbon = input$prevalence_plot_ribbon,
        line = input$prevalence_plot_line
      )
  })
  output$prevalence_plot <- shiny::renderUI({
    x <- getPrevalencePlot()
    renderInteractivePlot(x, input$prevalence_plot_interactive)
  })
  output$prevalence_plot_download <- shiny::downloadHandler(
    filename = "plot_prevalence.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getPrevalencePlot(),
        width = as.numeric(input$prevalence_plot_width),
        height = as.numeric(input$prevalence_plot_height),
        units = input$prevalence_plot_units,
        dpi = as.numeric(input$prevalence_plot_dpi)
      )
    }
  )
  getPrevalencePlotPopulation <- shiny::reactive({
    getPrevalenceData() |>
      IncidencePrevalence::plotPrevalencePopulation(
        facet = input$prevalence_plot_population_facet,
        colour = input$prevalence_plot_population_colour
      )
  })
  output$prevalence_plot_population <- shiny::renderUI({
    x <- getPrevalencePlotPopulation()
    renderInteractivePlot(x, input$prevalence_plot_population_interactive)
  })
  # prevalence_attrition -----
  ## update message if filter is changed
  shiny::observeEvent(input$prevalence_attrition_cdm_name,
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("FALSE",
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("FALSE",
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("point prevalence",
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_attrition_denominator_age_group,
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_attrition_denominator_days_prior_observation,
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_attrition_denominator_end_date,
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("FALSE",
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_attrition_denominator_sex,
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("2017-01-01",
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("None",
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent("0 to Inf",
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$prevalence_attrition_variable_name,
    {
      updateButtons$prevalence_attrition <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$prevalence_attrition, {
    if (updateButtons$prevalence_attrition == TRUE) {
      output$update_message_prevalence_attrition <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_prevalence_attrition <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_prevalence_attrition, {
    updateButtons$prevalence_attrition <- FALSE
  })

  ## get prevalence_attrition data
  getPrevalenceAttritionData <- shiny::eventReactive(input$update_prevalence_attrition, {
    data[["prevalence_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$prevalence_attrition_cdm_name,
        .data$variable_name %in% input$prevalence_attrition_variable_name
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_complete_database_intervals %in% "FALSE",
        .data$analysis_full_contribution %in% "FALSE",
        .data$analysis_type %in% "point prevalence",
        .data$denominator_age_group %in% input$prevalence_attrition_denominator_age_group,
        .data$denominator_days_prior_observation %in% input$prevalence_attrition_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$prevalence_attrition_denominator_end_date,
        .data$denominator_requirements_at_entry %in% "FALSE",
        .data$denominator_sex %in% input$prevalence_attrition_denominator_sex,
        .data$denominator_start_date %in% "2017-01-01",
        .data$denominator_target_cohort_name %in% "None",
        .data$denominator_time_at_risk %in% "0 to Inf"
      )
  })
  getPrevalenceAttritionTidy <- shiny::reactive({
    tidyDT(getPrevalenceAttritionData(), input$prevalence_attrition_tidy_columns, input$prevalence_attrition_tidy_pivot_estimates)
  })
  output$prevalence_attrition_tidy <- DT::renderDT({
    getPrevalenceAttritionTidy()
  })
  output$prevalence_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getPrevalenceAttritionData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getPrevalenceAttritionTable <- shiny::reactive({
    res <- getPrevalenceAttritionData()
    res |>
      IncidencePrevalence::tablePrevalenceAttrition(
        header = input$prevalence_attrition_table_header,
        settingsColumn = omopgenerics::settingsColumns(res),
        groupColumn = input$prevalence_attrition_table_group_column,
        hide = input$prevalence_attrition_table_hide
      )
  })
  output$prevalence_attrition_table <- gt::render_gt({
    getPrevalenceAttritionTable()
  })
  output$prevalence_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_prevalence_attrition.", input$prevalence_attrition_table_format),
    content = function(file) {
      gt::gtsave(getPrevalenceAttritionTable(), file)
    }
  )
}
