# Generated by OmopViewer 0.4.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = "Uptake of meningococcal vaccines in Europe",
  theme = bslib::bs_theme(bootswatch = "flatly"),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  # bslib::nav_panel(
  #   title = "Summary",
  #   icon = shiny::icon("file-alt"),
  #   bslib::card(
  #     bslib::card_header("Explore results"),
  #     shiny::tags$div(
  #       class = "mb-2",
  #       shinyTree::shinyTree("summary_cdm_name", theme = "proton", themeIcons = FALSE),
  #       shinyTree::shinyTree("summary_packages", theme = "proton", themeIcons = FALSE),
  #       shinyTree::shinyTree("summary_min_cell_count", theme = "proton", themeIcons = FALSE),
  #       shinyTree::shinyTree("summary_panels", theme = "proton", themeIcons = FALSE)
  #     ),
  #     full_screen = TRUE
  #   )
  # ),
  bslib::nav_menu(
    title = "Database details",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("clipboard-list"),
      #bslib::layout_sidebar(
        # sidebar = bslib::sidebar(
        #   shinyWidgets::pickerInput(
        #     inputId = "summarise_omop_snapshot_cdm_name",
        #     label = "CDM name",
        #     choices = choices$summarise_omop_snapshot_cdm_name,
        #     selected = selected$summarise_omop_snapshot_cdm_name,
        #     multiple = TRUE,
        #     options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        #   ),
        #   shinyWidgets::pickerInput(
        #     inputId = "summarise_omop_snapshot_variable_name",
        #     label = "Variable name",
        #     choices = choices$summarise_omop_snapshot_variable_name,
        #     selected = selected$summarise_omop_snapshot_variable_name,
        #     multiple = TRUE,
        #     options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        #   ),
        #   position = "left"
        # ),
        shiny::actionButton(
          inputId = "update_summarise_omop_snapshot",
          label = "Update content",
          width = "200px"
        ),
        shiny::div(shiny::textOutput(outputId = "update_message_summarise_omop_snapshot"), class = "ov_update_button"),
        bslib::navset_card_tab(
          # bslib::nav_panel(
          #   title = "Tidy",
          #   bslib::card(
          #     full_screen = TRUE,
          #     bslib::card_header(
          #       bslib::popover(
          #         shiny::icon("download"),
          #         shiny::downloadButton(outputId = "summarise_omop_snapshot_tidy_download", label = "Download csv")
          #       ),
          #       class = "text-end"
          #     ),
          #     bslib::layout_sidebar(
          #       sidebar = bslib::sidebar(
          #         shinyWidgets::pickerInput(
          #           inputId = "summarise_omop_snapshot_tidy_columns",
          #           label = "Columns",
          #           choices = c("cdm_name", "variable_name", "variable_level"),
          #           selected = c("cdm_name", "variable_name", "variable_level"),
          #           multiple = TRUE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         shiny::checkboxInput(
          #           inputId = "summarise_omop_snapshot_tidy_pivot_estimates",
          #           label = "Pivot estimates",
          #           value = TRUE
          #         ),
          #         position = "right"
          #       ),
          #       DT::DTOutput("summarise_omop_snapshot_tidy") |>
          #         shinycssloaders::withSpinner()
          #     )
          #   )
          # ),
          bslib::nav_panel(
            title = "Table Snapshot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_omop_snapshot_table") |>
                shinycssloaders::withSpinner()
            )
          )
      )
    ),
    bslib::nav_panel(
      title = "Observation period",
      icon = shiny::icon("eye"),
      #bslib::layout_sidebar(
        # sidebar = bslib::sidebar(
        #   # shinyWidgets::pickerInput(
        #   #   inputId = "summarise_observation_period_cdm_name",
        #   #   label = "CDM name",
        #   #   choices = choices$summarise_observation_period_cdm_name,
        #   #   selected = selected$summarise_observation_period_cdm_name,
        #   #   multiple = TRUE,
        #   #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        #   # ),
        #   shinyWidgets::pickerInput(
        #     inputId = "summarise_observation_period_observation_period_ordinal",
        #     label = "Observation period ordinal",
        #     choices = choices$summarise_observation_period_observation_period_ordinal,
        #     selected = selected$summarise_observation_period_observation_period_ordinal,
        #     multiple = TRUE,
        #     options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        #   ),
        #   shinyWidgets::pickerInput(
        #     inputId = "summarise_observation_period_variable_name",
        #     label = "Variable name",
        #     choices = choices$summarise_observation_period_variable_name,
        #     selected = selected$summarise_observation_period_variable_name,
        #     multiple = TRUE,
        #     options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        #   ),
        #   shinyWidgets::pickerInput(
        #     inputId = "summarise_observation_period_estimate_name",
        #     label = "Estimate name",
        #     choices = choices$summarise_observation_period_estimate_name,
        #     selected = selected$summarise_observation_period_estimate_name,
        #     multiple = TRUE,
        #     options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        #   ),
        #   position = "left"
        # # ),
        shiny::actionButton(
          inputId = "update_summarise_observation_period",
          label = "Update content",
          width = "200px"
        ),
        shiny::div(shiny::textOutput(outputId = "update_message_summarise_observation_period"), class = "ov_update_button"),
        bslib::navset_card_tab(
          # bslib::nav_panel(
          #   title = "Tidy",
          #   bslib::card(
          #     full_screen = TRUE,
          #     bslib::card_header(
          #       bslib::popover(
          #         shiny::icon("download"),
          #         shiny::downloadButton(outputId = "summarise_observation_period_tidy_download", label = "Download csv")
          #       ),
          #       class = "text-end"
          #     ),
          #     bslib::layout_sidebar(
          #       sidebar = bslib::sidebar(
          #         shinyWidgets::pickerInput(
          #           inputId = "summarise_observation_period_tidy_columns",
          #           label = "Columns",
          #           choices = c("cdm_name", "observation_period_ordinal", "variable_name", "variable_level"),
          #           selected = c("cdm_name", "observation_period_ordinal", "variable_name", "variable_level"),
          #           multiple = TRUE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         shiny::checkboxInput(
          #           inputId = "summarise_observation_period_tidy_pivot_estimates",
          #           label = "Pivot estimates",
          #           value = TRUE
          #         ),
          #         position = "right"
          #       ),
          #       DT::DTOutput("summarise_observation_period_tidy") |>
          #         shinycssloaders::withSpinner()
          #     )
          #   )
          # ),
          bslib::nav_panel(
            title = "Table Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_observation_period_table") |>
                shinycssloaders::withSpinner()
            )
          ),
          bslib::nav_panel(
            title = "Plot Observation period",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "summarise_observation_period_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "summarise_observation_period_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "summarise_observation_period_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_variable",
                    label = "Variable",
                    choices = c("Number subjects", "Records per person", "Duration", "Days to next observation period"),
                    selected = "Number subjects",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_plot_type",
                    label = "Plot type",
                    choices = c("boxplot", "barplot", "densityplot"),
                    selected = "barplot",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_observation_period_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "observation_period_ordinal"),
                    selected = "observation_period_ordinal",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("summarise_observation_period_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
    )
  ),
  bslib::nav_menu(
    title = "Patient characteristics",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Cohort Characteristics",
      icon = shiny::icon("users-gear"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cdm_name",
            label = "CDM name",
            choices = choices$summarise_characteristics_cdm_name,
            selected = selected$summarise_characteristics_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_cohort_name",
            label = "Cohort name",
            choices = choices$summarise_characteristics_cohort_name,
            selected = selected$summarise_characteristics_cohort_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_sex",
            label = "Sex",
            choices = choices$summarise_characteristics_sex,
            selected = selected$summarise_characteristics_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_age_group",
            label = "Age group",
            choices = choices$summarise_characteristics_age_group,
            selected = selected$summarise_characteristics_age_group,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_age",
            label = "Age",
            choices = choices$summarise_characteristics_age,
            selected = selected$summarise_characteristics_age,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_variable_name",
            label = "Variable name",
            choices = choices$summarise_characteristics_variable_name,
            selected = selected$summarise_characteristics_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_characteristics_estimate_name",
            label = "Estimate name",
            choices = choices$summarise_characteristics_estimate_name,
            selected = selected$summarise_characteristics_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        shiny::actionButton(
          inputId = "update_summarise_characteristics",
          label = "Update content",
          width = "200px"
        ),
        shiny::div(shiny::textOutput(outputId = "update_message_summarise_characteristics"), class = "ov_update_button"),
        bslib::navset_card_tab(
          # bslib::nav_panel(
          #   title = "Tidy",
          #   bslib::card(
          #     full_screen = TRUE,
          #     bslib::card_header(
          #       bslib::popover(
          #         shiny::icon("download"),
          #         shiny::downloadButton(outputId = "summarise_characteristics_tidy_download", label = "Download csv")
          #       ),
          #       class = "text-end"
          #     ),
          #     bslib::layout_sidebar(
          #       sidebar = bslib::sidebar(
          #         shinyWidgets::pickerInput(
          #           inputId = "summarise_characteristics_tidy_columns",
          #           label = "Columns",
          #           choices = c("cdm_name", "cohort_name", "sex", "age_group", "age", "table_name", "variable_name", "variable_level"),
          #           selected = c("cdm_name", "cohort_name", "sex", "age_group", "age", "variable_name", "variable_level"),
          #           multiple = TRUE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         shiny::checkboxInput(
          #           inputId = "summarise_characteristics_tidy_pivot_estimates",
          #           label = "Pivot estimates",
          #           value = TRUE
          #         ),
          #         position = "right"
          #       ),
          #       DT::DTOutput("summarise_characteristics_tidy") |>
          #         shinycssloaders::withSpinner()
          #     )
          #   )
          # ),
          bslib::nav_panel(
            title = "Table Characteristics",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_characteristics_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_characteristics_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("sex", "age_group", "age", "variable_name", "variable_level", "estimate_name"),
                      input_id = "summarise_characteristics_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = c("cdm_name", "cohort_name"),
                      input_id = "summarise_characteristics_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = character(),
                      input_id = "summarise_characteristics_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = "table_name",
                      input_id = "summarise_characteristics_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("summarise_characteristics_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          # bslib::nav_panel(
          #   title = "Plot Characteristics",
          #   bslib::card(
          #     full_screen = TRUE,
          #     bslib::card_header(
          #       bslib::popover(
          #         shiny::icon("download"),
          #         shiny::numericInput(
          #           inputId = "summarise_characteristics_plot_width",
          #           label = "Width",
          #           value = 15
          #         ),
          #         shiny::numericInput(
          #           inputId = "summarise_characteristics_plot_height",
          #           label = "Height",
          #           value = 15
          #         ),
          #         shinyWidgets::pickerInput(
          #           inputId = "summarise_characteristics_plot_units",
          #           label = "Units",
          #           choices = c("px", "cm", "inch"),
          #           selected = "cm",
          #           multiple = FALSE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         shiny::numericInput(
          #           inputId = "summarise_characteristics_plot_dpi",
          #           label = "DPI",
          #           value = 300
          #         ),
          #         shiny::downloadButton(outputId = "summarise_characteristics_plot_download", label = "Download plot")
          #       ),
          #       class = "text-end"
          #     ),
          #     bslib::layout_sidebar(
          #       sidebar = bslib::sidebar(
          #         shinyWidgets::materialSwitch(
          #           inputId = "summarise_characteristics_plot_interactive",
          #           label = "Interactive",
          #           value = TRUE
          #         ),
          #         shinyWidgets::pickerInput(
          #           inputId = "summarise_characteristics_plot_plot_type",
          #           label = "Plot type",
          #           choices = c("boxplot", "barplot", "scatterplot"),
          #           selected = "boxplot",
          #           multiple = FALSE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         shinyWidgets::pickerInput(
          #           inputId = "summarise_characteristics_plot_facet",
          #           label = "Facet",
          #           choices = c("cdm_name", "cohort_name", "sex", "age_group", "age"),
          #           selected = "cdm_name",
          #           multiple = TRUE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         shinyWidgets::pickerInput(
          #           inputId = "summarise_characteristics_plot_colour",
          #           label = "Colour",
          #           choices = c("cdm_name", "cohort_name", "sex", "age_group", "age"),
          #           selected = "cohort_name",
          #           multiple = TRUE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         position = "right"
          #       ),
          #       shiny::uiOutput("summarise_characteristics_plot") |>
          #         shinycssloaders::withSpinner()
          #     )
          #   )
          # )
        )
      )
    )
  ),
  bslib::nav_menu(
    title = "Vaccine coverage",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Prevalence",
      icon = shiny::icon("chart-column"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "prevalence_cdm_name",
            label = "CDM name",
            choices = choices$prevalence_cdm_name,
            selected = selected$prevalence_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_outcome_cohort_name",
            label = "Outcome cohort name",
            choices = choices$prevalence_outcome_cohort_name,
            selected = "men_b",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_prevalence_start_date",
            label = "Prevalence start date",
            choices = choices$prevalence_prevalence_start_date,
            selected = selected$prevalence_prevalence_start_date,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_prevalence_end_date",
            label = "Prevalence end date",
            choices = choices$prevalence_prevalence_end_date,
            selected = selected$prevalence_prevalence_end_date,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_analysis_interval",
            label = "Analysis interval",
            choices = choices$prevalence_analysis_interval,
            selected = selected$prevalence_analysis_interval,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_analysis_complete_database_intervals",
          #   label = "Analysis complete database intervals",
          #   choices = choices$prevalence_analysis_complete_database_intervals,
          #   selected = selected$prevalence_analysis_complete_database_intervals,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_analysis_full_contribution",
          #   label = "Analysis full contribution",
          #   choices = choices$prevalence_analysis_full_contribution,
          #   selected = selected$prevalence_analysis_full_contribution,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_analysis_type",
          #   label = "Analysis type",
          #   choices = choices$prevalence_analysis_type,
          #   selected = selected$prevalence_analysis_type,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_denominator_age_group",
            label = "Denominator age group",
            choices = c("1", "2", "12 to 18", "18"),
            selected = "1",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_denominator_days_prior_observation",
            label = "Denominator days prior observation",
            choices = c("0", "309", "674", "2190"),
            selected = "0",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_denominator_end_date",
            label = "Denominator end date",
            choices = choices$prevalence_denominator_end_date,
            selected = selected$prevalence_denominator_end_date,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_denominator_requirements_at_entry",
          #   label = "Denominator requirements at entry",
          #   choices = choices$prevalence_denominator_requirements_at_entry,
          #   selected = selected$prevalence_denominator_requirements_at_entry,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_denominator_sex",
            label = "Denominator sex",
            choices = choices$prevalence_denominator_sex,
            selected = selected$prevalence_denominator_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_denominator_start_date",
          #   label = "Denominator start date",
          #   choices = choices$prevalence_denominator_start_date,
          #   selected = selected$prevalence_denominator_start_date,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_denominator_target_cohort_name",
          #   label = "Denominator target cohort name",
          #   choices = choices$prevalence_denominator_target_cohort_name,
          #   selected = selected$prevalence_denominator_target_cohort_name,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_denominator_time_at_risk",
          #   label = "Denominator time at risk",
          #   choices = choices$prevalence_denominator_time_at_risk,
          #   selected = selected$prevalence_denominator_time_at_risk,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_variable_name",
            label = "Variable name",
            choices = choices$prevalence_variable_name,
            selected = selected$prevalence_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_estimate_name",
            label = "Estimate name",
            choices = choices$prevalence_estimate_name,
            selected = selected$prevalence_estimate_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        shiny::actionButton(
          inputId = "update_prevalence",
          label = "Update content",
          width = "200px"
        ),
        shiny::div(shiny::textOutput(outputId = "update_message_prevalence"), class = "ov_update_button"),
        bslib::navset_card_tab(
          # bslib::nav_panel(
          #   title = "Tidy",
          #   bslib::card(
          #     full_screen = TRUE,
          #     bslib::card_header(
          #       bslib::popover(
          #         shiny::icon("download"),
          #         shiny::downloadButton(outputId = "prevalence_tidy_download", label = "Download csv")
          #       ),
          #       class = "text-end"
          #     ),
          #     bslib::layout_sidebar(
          #       sidebar = bslib::sidebar(
          #         shinyWidgets::pickerInput(
          #           inputId = "prevalence_tidy_columns",
          #           label = "Columns",
          #           choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level"),
          #           selected = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "variable_name", "variable_level"),
          #           multiple = TRUE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         shiny::checkboxInput(
          #           inputId = "prevalence_tidy_pivot_estimates",
          #           label = "Pivot estimates",
          #           value = TRUE
          #         ),
          #         position = "right"
          #       ),
          #       DT::DTOutput("prevalence_tidy") |>
          #         shinycssloaders::withSpinner()
          #     )
          #   )
          # ),
          bslib::nav_panel(
            title = "Table Prevalence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "prevalence_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = c("prevalence_start_date", "prevalence_end_date", "denominator_age_group", "denominator_sex"),
                      input_id = "prevalence_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "estimate_name",
                      input_id = "prevalence_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "outcome_cohort_name"),
                      input_id = "prevalence_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("denominator_cohort_name", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                      input_id = "prevalence_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("prevalence_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot Prevalence",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::numericInput(
                    inputId = "prevalence_plot_width",
                    label = "Width",
                    value = 15
                  ),
                  shiny::numericInput(
                    inputId = "prevalence_plot_height",
                    label = "Height",
                    value = 15
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_units",
                    label = "Units",
                    choices = c("px", "cm", "inch"),
                    selected = "cm",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::numericInput(
                    inputId = "prevalence_plot_dpi",
                    label = "DPI",
                    value = 300
                  ),
                  shiny::downloadButton(outputId = "prevalence_plot_download", label = "Download plot")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "prevalence_plot_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_x",
                    label = "x axis",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "prevalence_start_date",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_facet",
                    label = "Facet",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_colour",
                    label = "Colour",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "outcome_cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "prevalence_plot_ribbon",
                    label = "Ribbon",
                    value = TRUE
                  ),
                  shinyWidgets::materialSwitch(
                    inputId = "prevalence_plot_line",
                    label = "Line",
                    value = TRUE
                  ),
                  position = "right"
                ),
                shiny::uiOutput("prevalence_plot") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Plot population",
            bslib::card(
              full_screen = TRUE,
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::materialSwitch(
                    inputId = "prevalence_plot_population_interactive",
                    label = "Interactive",
                    value = TRUE
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_population_facet",
                    label = "Facet",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "cdm_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_plot_population_colour",
                    label = "Colour",
                    choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "prevalence_start_date", "prevalence_end_date", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                    selected = "outcome_cohort_name",
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  position = "right"
                ),
                shiny::uiOutput("prevalence_plot_population") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    ),
    bslib::nav_panel(
      title = "Prevalence Attrition",
      icon = shiny::icon("layer-group"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_cdm_name",
            label = "CDM name",
            choices = choices$prevalence_attrition_cdm_name,
            selected = selected$prevalence_attrition_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_attrition_analysis_complete_database_intervals",
          #   label = "Analysis complete database intervals",
          #   choices = choices$prevalence_attrition_analysis_complete_database_intervals,
          #   selected = selected$prevalence_attrition_analysis_complete_database_intervals,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_attrition_analysis_full_contribution",
          #   label = "Analysis full contribution",
          #   choices = choices$prevalence_attrition_analysis_full_contribution,
          #   selected = selected$prevalence_attrition_analysis_full_contribution,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_attrition_analysis_type",
          #   label = "Analysis type",
          #   choices = choices$prevalence_attrition_analysis_type,
          #   selected = selected$prevalence_attrition_analysis_type,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_denominator_age_group",
            label = "Denominator age group",
            choices = c("1", "2", "12 to 18", "18"),
            selected = "1",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_denominator_days_prior_observation",
            label = "Denominator days prior observation",
            choices = c("0", "309", "674", "2190"),
            selected = "0",
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_denominator_end_date",
            label = "Denominator end date",
            choices = choices$prevalence_attrition_denominator_end_date,
            selected = selected$prevalence_attrition_denominator_end_date,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_attrition_denominator_requirements_at_entry",
          #   label = "Denominator requirements at entry",
          #   choices = choices$prevalence_attrition_denominator_requirements_at_entry,
          #   selected = selected$prevalence_attrition_denominator_requirements_at_entry,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_denominator_sex",
            label = "Denominator sex",
            choices = choices$prevalence_attrition_denominator_sex,
            selected = selected$prevalence_attrition_denominator_sex,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_attrition_denominator_start_date",
          #   label = "Denominator start date",
          #   choices = choices$prevalence_attrition_denominator_start_date,
          #   selected = selected$prevalence_attrition_denominator_start_date,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_attrition_denominator_target_cohort_name",
          #   label = "Denominator target cohort name",
          #   choices = choices$prevalence_attrition_denominator_target_cohort_name,
          #   selected = selected$prevalence_attrition_denominator_target_cohort_name,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          # shinyWidgets::pickerInput(
          #   inputId = "prevalence_attrition_denominator_time_at_risk",
          #   label = "Denominator time at risk",
          #   choices = choices$prevalence_attrition_denominator_time_at_risk,
          #   selected = selected$prevalence_attrition_denominator_time_at_risk,
          #   multiple = TRUE,
          #   options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          # ),
          shinyWidgets::pickerInput(
            inputId = "prevalence_attrition_variable_name",
            label = "Variable name",
            choices = choices$prevalence_attrition_variable_name,
            selected = selected$prevalence_attrition_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        shiny::actionButton(
          inputId = "update_prevalence_attrition",
          label = "Update content",
          width = "200px"
        ),
        shiny::div(shiny::textOutput(outputId = "update_message_prevalence_attrition"), class = "ov_update_button"),
        bslib::navset_card_tab(
          # bslib::nav_panel(
          #   title = "Tidy",
          #   bslib::card(
          #     full_screen = TRUE,
          #     bslib::card_header(
          #       bslib::popover(
          #         shiny::icon("download"),
          #         shiny::downloadButton(outputId = "prevalence_attrition_tidy_download", label = "Download csv")
          #       ),
          #       class = "text-end"
          #     ),
          #     bslib::layout_sidebar(
          #       sidebar = bslib::sidebar(
          #         shinyWidgets::pickerInput(
          #           inputId = "prevalence_attrition_tidy_columns",
          #           label = "Columns",
          #           choices = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "reason", "reason_id", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_sex", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk", "variable_name", "variable_level"),
          #           selected = c("cdm_name", "denominator_cohort_name", "outcome_cohort_name", "reason", "reason_id", "variable_name", "variable_level"),
          #           multiple = TRUE,
          #           options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          #         ),
          #         shiny::checkboxInput(
          #           inputId = "prevalence_attrition_tidy_pivot_estimates",
          #           label = "Pivot estimates",
          #           value = TRUE
          #         ),
          #         position = "right"
          #       ),
          #       DT::DTOutput("prevalence_attrition_tidy") |>
          #         shinycssloaders::withSpinner()
          #     )
          #   )
          # ),
          bslib::nav_panel(
            title = "Table Prevalence Attrition",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "prevalence_attrition_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "prevalence_attrition_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  sortable::bucket_list(
                    header = NULL,
                    sortable::add_rank_list(
                      text = "None",
                      labels = "reason",
                      input_id = "prevalence_attrition_table_none"
                    ),
                    sortable::add_rank_list(
                      text = "Header",
                      labels = "variable_name",
                      input_id = "prevalence_attrition_table_header"
                    ),
                    sortable::add_rank_list(
                      text = "Group columns",
                      labels = c("cdm_name", "outcome_cohort_name"),
                      input_id = "prevalence_attrition_table_group_column"
                    ),
                    sortable::add_rank_list(
                      text = "Hide",
                      labels = c("denominator_cohort_name", "estimate_name", "reason_id", "variable_level", "analysis_interval", "analysis_complete_database_intervals", "analysis_full_contribution", "analysis_type", "denominator_age_group", "denominator_sex", "denominator_days_prior_observation", "denominator_end_date", "denominator_requirements_at_entry", "denominator_start_date", "denominator_target_cohort_name", "denominator_time_at_risk"),
                      input_id = "prevalence_attrition_table_hide"
                    )
                  ),
                  position = "right"
                ),
                gt::gt_output("prevalence_attrition_table") |>
                  shinycssloaders::withSpinner()
              )
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.4.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
